### ISSUE TITLE
Template documentation links broken

### ISSUE THREAD

**Issue by jdrew82** [nautobot/cookiecutter-nautobot-app#151] opened 2024-08-22 18:22 UTC
### Environment

* Python version:  3.8
* cookiecutter-nautobot-app template version:  2.3.0

### Observed Behavior
Clicking links on RTD site for nautobot-app and nautobot-app-ssot results in a 404 broken link error. It appears the links work in the README.

### Expected Behavior
Expected to see the documentation on the relevant template.

### Steps to Reproduce

1. Go to RTD at https://docs.nautobot.com/projects/cookiecutter-nautobot-app/en/latest/.
2.Click nautobot-app or nautobot-app-ssot URL link.
3. See 404 error page.

**Comment by gsnider2195** [comment] 2024-10-02 17:29
Duplicate of #109

**Closed by gsnider2195** 2024-10-02 17:29 UTC
